Add link to the IOMB
ACCESS-Hive/ACCESS-Hive pull request #128
Opened 2022-10-11 01:26 UTC by rbeucher

# ACCESS Community Hive 

Thank you for submitting a pull request to the ACCESS Hive Project. 

## Description

Add link to the International Ocean Model Benchmarking (IOMB) Package

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue, e.g. dead links)
- [X] New link / content

## Checklist:

- [ ] The new content is accessible and located in the appropriate section.
- [ ] My changes do not break navigation and do not generate new warnings
- [ ] I have checked that the links are valid and point to the intended content.
- [ ] I have checked my code/text and corrected any misspellings

Please tag the **reviewers team** in a comment below by prepending an `@` in front of `ACCESS-Hive/reviewers` when ready.

2022-10-11 21:55 UTC, ccarouge requested changes
Again, I think we need to discuss how we are to add the tags and how the reviewer will know if it's the right level of tagging

2022-10-11 21:55 UTC, ccarouge commented on docs/model_evaluation/bgc_ocean.md
> +The International Ocean Model Benchmarking (IOMB) Package is used to evaluate marine biogeochemistry models through comparisons with observations. IOMB provides a variety of in-depth diagnostics of m
```suggestion
The International Ocean Model Benchmarking (IOMB) Package is used to evaluate marine biogeochemistry models through comparisons with observations. IOMB provides a variety of in-depth diagnostics of marine biogeochemical model variables on annual and inter-annual time scales. It compares a growing number of variables with site-based, transect, regional, and global observational data sets, and scores model performance based on a combination of bias, RMSE, and seasonal cycle metrics. IOMB is useful for the detailed exploration of ocean biogeochemical model responses and provides an interactive interface designed to enable the user to more rapidly understand the underlying drivers of those responses. IOMB was first applied to evaluate uncertainties associated with marine aerosol precursors [(Ogunro et al., 2018)](https://www.mdpi.com/2073-4433/9/5/184).
```

2022-10-11 21:55 UTC, ccarouge commented on docs/model_evaluation/bgc_ocean.md
> +IOMB uses the same code base as the International Land Model Benchmarking (ILAMB) Package, so some of the links below refer to ILAMB instead of IOMB.
```suggestion
IOMB uses the same code base as the International Land Model Benchmarking (ILAMB) Package, so some of the links above refer to ILAMB instead of IOMB.
```
And place this before the paragraph with the description.

2022-10-11 21:55 UTC, ccarouge commented on docs/model_evaluation/bgc_ocean.md
> +## [The International Ocean Model Benchmarking (IOMB)][IOMB-web]  {{ recom }}
Again, are we sure of the level of tagging? ILAMB I agree with recommended because we know it is becoming a standard for land. Is IOMB a standard for biogeochemistry? Is it developed enough? Used?

2022-10-11 22:27 UTC, rbeucher commented on docs/model_evaluation/bgc_ocean.md
> +## [The International Ocean Model Benchmarking (IOMB)][IOMB-web]  {{ recom }}
Changed to community. You are right.

2022-10-12 00:59 UTC, ccarouge approved these changes
All good.

2022-10-12 01:00 UTC, merged